cursor #dee4e4
cursor_text_color #bec8ca

foreground            #dee4e4
background            #0e1415
selection_foreground  #1c3437
selection_background  #b1cbcf
url_color             #81d3de

color0   #0e1415
color1   #ff72a3
color2   #6fde79
color3   #fff572
color4   #68c6d2
color5   #175d66
color6   #81d3de
color7   #dbe7e9
color8   #858f90
color9   #ff9fc0
color10  #a5ffae
color11  #fff8a5
color12  #9de9f4
color13  #b4f6ff
color14  #cef9ff
color15  #f8feff
