cursor #f0dedf
cursor_text_color #d7c1c2

foreground            #f0dedf
background            #1a1112
selection_foreground  #44292b
selection_background  #e5bdbf
url_color             #ffb2b8

color0   #1a1112
color1   #ff7274
color2   #9cff7f
color3   #ffe372
color4   #f29aa1
color5   #763439
color6   #ffb2b8
color7   #ffeff0
color8   #a5999a
color9   #ff9fa0
color10  #b9ffa5
color11  #ffeda5
color12  #ffbdc2
color13  #ffc9cd
color14  #ffdcdf
color15  #fff8f9
