cursor #dde4e2
cursor_text_color #bec9c6

foreground            #dde4e2
background            #0e1514
selection_foreground  #1c3532
selection_background  #b1ccc8
url_color             #81d5cc

color0   #0e1514
color1   #f49c6e
color2   #6ad572
color3   #fff472
color4   #6acac0
color5   #1b625a
color6   #81d5cc
color7   #d2dfde
color8   #808a89
color9   #ffc09f
color10  #a5ffac
color11  #fff8a5
color12  #9beae1
color13  #b8fff7
color14  #d1fffa
color15  #f8fffe
