github.com:
    git_protocol: https
    users:
        mckahz:
            oauth_token: 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
    user: mckahz
    oauth_token: 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
