nix = require("nix")

hl.bind("SUPER + 1", hl.dsp.focus({ workspace = 1 }))
hl.bind("SUPER + 2", hl.dsp.focus({ workspace = 2 }))
hl.bind("SUPER + 3", hl.dsp.focus({ workspace = 3 }))
hl.bind("SUPER + 4", hl.dsp.focus({ workspace = 4 }))
hl.bind("SUPER + 5", hl.dsp.focus({ workspace = 5 }))
hl.bind("SUPER + 6", hl.dsp.focus({ workspace = 6 }))
hl.bind("SUPER + 7", hl.dsp.focus({ workspace = 7 }))
hl.bind("SUPER + 8", hl.dsp.focus({ workspace = 8 }))
hl.bind("SUPER + 9", hl.dsp.focus({ workspace = 9 }))
hl.bind("SUPER + CONTROL + 1", hl.dsp.window.move({ workspace = 1 }))
hl.bind("SUPER + CONTROL + 2", hl.dsp.window.move({ workspace = 2 }))
hl.bind("SUPER + CONTROL + 3", hl.dsp.window.move({ workspace = 3 }))
hl.bind("SUPER + CONTROL + 4", hl.dsp.window.move({ workspace = 4 }))
hl.bind("SUPER + CONTROL + 5", hl.dsp.window.move({ workspace = 5 }))
hl.bind("SUPER + CONTROL + 6", hl.dsp.window.move({ workspace = 6 }))
hl.bind("SUPER + CONTROL + 7", hl.dsp.window.move({ workspace = 7 }))
hl.bind("SUPER + CONTROL + 8", hl.dsp.window.move({ workspace = 8 }))
hl.bind("SUPER + CONTROL + 9", hl.dsp.window.move({ workspace = 9 }))

hl.bind("SUPER + H", (hl.dsp.focus({ direction = 'left' })))
hl.bind("SUPER + J", (hl.dsp.focus({ direction = 'down' })))
hl.bind("SUPER + K", (hl.dsp.focus({ direction = 'up' })))
hl.bind("SUPER + L", (hl.dsp.focus({ direction = 'right' })))

hl.bind("SUPER + SHIFT + H", (hl.dsp.layout('orientationleft')))
hl.bind("SUPER + SHIFT + J", (hl.dsp.layout('orientationbottom')))
hl.bind("SUPER + SHIFT + K", (hl.dsp.layout('orientationtop')))
hl.bind("SUPER + SHIFT + L", (hl.dsp.layout('orientationright')))

hl.bind("SUPER + CONTROL + H", (hl.dsp.window.move({ direction = 'left' })))
hl.bind("SUPER + CONTROL + J", (hl.dsp.window.move({ direction = 'down' })))
hl.bind("SUPER + CONTROL + K", (hl.dsp.window.move({ direction = 'up' })))
hl.bind("SUPER + CONTROL + L", (hl.dsp.window.move({ direction = 'right' })))

hl.bind("SUPER + F", (hl.dsp.window.fullscreen({ mode = 'maximized', action = 'toggle' })))
hl.bind("SUPER + Q", (hl.dsp.window.close()), { locked = true })
hl.bind("SUPER + RETURN", (hl.dsp.exec_cmd('kitty')))
hl.bind("SUPER + SPACE", (hl.dsp.exec_cmd(nix.noctalia.. ' msg panel-toggle launcher')))
hl.bind("SUPER + SHIFT + F", (hl.dsp.window.fullscreen({ mode = 'fullscreen', action = 'toggle' })))
hl.bind("SUPER + SHIFT + S", (hl.dsp.exec_cmd(nix.hyprshot .. ' -m region -o /home/mckahz/Pictures/Screenshots')))
hl.bind("SUPER + U", (hl.dsp.focus({ workspace = 'e-1' })))
hl.bind("SUPER + I", (hl.dsp.focus({ workspace = 'e+1' })))
hl.bind("SUPER + V", (hl.dsp.window.float({ action = 'toggle' })))
hl.bind("SUPER + Z", (hl.dsp.exec_cmd(nix.noctalia .. ' msg session lock')))

hl.bind("SUPER + equal", (hl.dsp.window.resize({ x = 100, y = 0, relative = true })), { repeating = true })
hl.bind("SUPER + minus", (hl.dsp.window.resize({ x = -100, y = 0, relative = true })), { repeating = true })
hl.bind("SUPER + mouse:272", (hl.dsp.window.drag()), { mouse = true })
hl.bind("SUPER + mouse:273", (hl.dsp.window.resize()), { mouse = true })
hl.bind("SUPER + mouse_down", (hl.dsp.focus({ workspace = 'e+1' })))
hl.bind("SUPER + mouse_up", (hl.dsp.focus({ workspace = 'e-1' })))

hl.bind("XF86AudioLowerVolume", (hl.dsp.exec_cmd(nix.wireplumber .. ' set-volume @DEFAULT_AUDIO_SINK@ 5%-')), { locked = true, repeating = true })
hl.bind("XF86AudioMicMute", (hl.dsp.exec_cmd(nix.wireplumber .. ' set-mute @DEFAULT_AUDIO_SOURCE@ toggle')), { locked = true, repeating = true })
hl.bind("XF86AudioMute", (hl.dsp.exec_cmd(nix.wireplumber .. ' set-mute @DEFAULT_AUDIO_SINK@ toggle')), { locked = true, repeating = true })
hl.bind("XF86AudioNext", (hl.dsp.exec_cmd(nix.playerctl .. ' next')), { locked = true })
hl.bind("XF86AudioPause", (hl.dsp.exec_cmd(nix.playerctl .. ' play-pause')), { locked = true })
hl.bind("XF86AudioPlay", (hl.dsp.exec_cmd(nix.playerctl .. ' play-pause')), { locked = true })
hl.bind("XF86AudioPrev", (hl.dsp.exec_cmd(nix.playerctl .. ' previous')), { locked = true })
hl.bind("XF86AudioRaiseVolume", (hl.dsp.exec_cmd(nix.wireplumber .. ' set-volume -l 1 @DEFAULT_AUDIO_SINK@ 5%+')), { locked = true, repeating = true })
hl.bind("XF86MonBrightnessDown", (hl.dsp.exec_cmd(nix.brightnessctl .. ' -e4 -n2 set 5%-')), { locked = true, repeating = true })
hl.bind("XF86MonBrightnessUp", (hl.dsp.exec_cmd(nix.brightnessctl .. ' -e4 -n2 set 5%+')), { locked = true, repeating = true })
